package game

var WinningCombinations = [8][3]Position{
	// Horizontal
	{TOP_LEFT, TOP_CENTER, TOP_RIGHT},
	{CENTER_LEFT, CENTER, CENTER_RIGHT},
	{BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT},

	// Vertical
	{TOP_LEFT, CENTER_LEFT, BOTTOM_LEFT},
	{TOP_CENTER, CENTER, BOTTOM_CENTER},
	{TOP_RIGHT, CENTER_RIGHT, BOTTOM_RIGHT},

	// Diagonal
	{TOP_LEFT, CENTER, BOTTOM_RIGHT},
	{BOTTOM_LEFT, CENTER, TOP_RIGHT},
}
